name: joshbeutephotography
favicon: null
layout_spectrum: 0.797474768711254
typography_spectrum: 0.3261780715547502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3610258193220943
  lightness: 0.063307442702353
  saturation: 0.6620116487611085
  rhythmicContrast: 0.7904868761543185
purpose: []
